### ISSUE TITLE
Database 스키마 ER다이어그램

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/GothamSubway#2]
![ER다이어그램](https://user-images.githubusercontent.com/69996028/102074790-a44cdc00-3e48-11eb-8dc8-e149dad96f21.png)

**Comment by kaiascezar** [comment]
![DB 스키마](https://user-images.githubusercontent.com/74527101/102157425-d13dd500-3ec2-11eb-9312-457a7316dd3d.JPG)

**Comment by kaiascezar** [comment]
![Uploading DB 스키마.JPG…]()

**Comment by kaiascezar** [comment]
![DB 스키마](https://user-images.githubusercontent.com/74527101/102163197-0996e080-3ece-11eb-8bc9-2bfc656de6fe.JPG)
